# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbfCw3GHEiCqwytuyMSLIrx2dg9pmRbH
"""

def WhoAmI():
  return('yy3674')

def getBondprice(y,face,couponRate,m,ppy):
  sumpvcf=0
  cf=face*couponRate/ppy
  if ppy==1:
    if i==m:
      cf=cf+face
    for i in range(1,m+1):
      pvf=(1+y)**-i
      sumpvcf=sumpvcf+cf*pvf
  elif ppy!=1:
    t=m*ppy
    for j in range(1,t+1):
      if j==m*ppy:
        cf=cf+face
      for j in range(1,m+1):
        pvf=(1+y)**-j
        sumpvcf=sumpvcf+cf*pvf
  return sumpvcf

y=0.03
face=2000000
couponRate=0.04
m=10
ppy=1
getBondPrice(y,face,couponRate,m,ppy)

def getBondDuration(y,face,couponRate,m,ppy):
  sumpvcf=0
  duration=0
  sumW=0
  cf=face*couponRate/ppy
  if ppy==1:
    for i in range(1,m+1):
      pvf=(1+y)**-i
      if i==m:
        cf=cf+face
      sumpvcf=sumpvcf+pvf*cf
      sumW=sumW+i*pvf*cf
    duration=sumW/sumpvcf

  if ppy!=1:
    t=m*ppy
    cf=face*couponRate/ppy
    for j in range(1,t+1):
      pvf=(1+y)**-j
      if j==m*ppy:
        cf=cf+face
      sumpvcf=sumpvcf+pvf*cf
      sumW=sumW+j*pvf*cf
    duration=sumW/sumpvcf

  return duration

getBondDuration(0.03,2000000,0.04,10,1)

def getBondPrice_E(face,couponRate,m,yc):
  sumpvcf=0
  cf=face*couponRate
  for t, yt in enumerate(yc,start=1):
    pvf=(1+yt)**-t
    if t==m:
      cf=cf+face
    sumpvcf=sumpvcf+cf*pvf
  return sumpvcf

yc=[.01,.015,.02,.025,.03]
getBondPrice_E(2000000,0.04,5,yc)

def getBondPrice_Z(face, couponRate, times, yc):
  sumpvcf=0
  cf=face*couponRate
  for t, y in zip(times,yc):
    pvf=(1+y)**-t
    if t==times[-1]:
      cf=cf+face
    sumpvcf=sumpvcf+cf*pvf
  return sumpvcf

face=2000000
couponRate=0.04
times=[1,1.5,3,4,7]
yc=[0.01,0.015,0.02,0.025,0.03]
getBondPrice_Z(face,couponRate,times,yc)

def FizzBuzz(start,end):
  outlist=[]
  for i in range(start,end+1):
    if i % 15==0:
      outlist.append('FizzBuzz')
    elif i % 3==0:
      outlist.append('Fizz')
    elif i % 5==0:
      outlist.append('Buzz')
    else:
      outlist.append(i)

  return outlist

FizzBuzz(1,15)